CREATE TABLE users (
    userId BIGINT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);