#!/bin/sh

staged=$(git diff --staged --name-only)

echo "Checking the code formatting with spotlessApply..."
./gradlew spotlessApply


for file in $staged; do
    if test -f "$file"; then
      git add "$file"
    fi
done